name: Deploy Pages
on: 
  push: 
    branches: [ main ]
permissions: 
  contents: read
  pages: write
  id-token: write
concurrency: 
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Install tools
        run: |
          nix-env -iA nixpkgs.babashka nixpkgs.clojure nixpkgs.nodejs_20 nixpkgs.zprint nixpkgs.clj-kondo
      - name: Generate + bundle
        run: |
          bb build:gen
          BASE_PATH="/foolsgoldtoshi-star-pond-highdesert/" bb pages:build
      - uses: actions/upload-pages-artifact@v3
        with: 
          path: web/build
      - uses: actions/deploy-pages@v4
